### ISSUE TITLE
[PE-D][Tester B] add command bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-1/tp#172]
![image.png](https://raw.githubusercontent.com/Richardtok/ped/main/files/4386d068-cf21-4e3e-a0f7-7f43c143fc0f.png)
As can be seen form the picture above I have the data but the command is inputted correctly however i keep getting error form it saying it does not exist eventhough in the folder it exist.
It is also the same  for any COMMAND_NAME, as can be seen the SORTING is also not working.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Richardtok/ped#2

**Comment by heejet** [comment]
![image](https://user-images.githubusercontent.com/88279614/229256473-f7d33ed4-90ae-4992-841c-85029791fc36.png)
