### ISSUE TITLE
[PE-D][Tester D] Storage does not reload all saved files when application is launch

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-1/tp#179]
When the programme is exited and relaunched, not all files that were added into the programme the previous session are reloaded.

As seen from the screenshot, files fish.txt, elephant.txt and charlie.txt is not listed when the programme is relaunched.

![image.png](https://raw.githubusercontent.com/kaceycsn/ped/main/files/e5fbea12-482f-4b76-929c-5cdee258b841.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kaceycsn/ped#4

**Comment by heejet** [comment]
I think it is better to include an error message to inform the user some data files are corrupted and would result in a loss of data
