### ISSUE TITLE
[PE-D][Tester D] Topological sort function does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-1/tp#183]
When topological sort command is called, entries listed does not follow topological ordering. 

Also, as seen from the screenshot, only entries from 'SORTING' topics are listed. Entries of other topics are omitted, and this does not cohere with the user guide.

![image.png](https://raw.githubusercontent.com/kaceycsn/ped/main/files/6ca838c2-aa00-400f-aa85-9b19abd437e9.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kaceycsn/ped#6

**Comment by heejet** [comment]
I think need to improve the explanation of the topo function
