### ISSUE TITLE
[PE-D][Tester A] Error when the data folder is deleted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-1/tp#184]
## Describe the bug
An error will be thrown when the user _accidentally_ delete data folder

## To Reproduce
1. User runs the .jar application
2. User _accidentally_ delete the data file
3. User tries to add a file to the program

## Expected behavior
This should be properly handled and the program should not crash.

## Screenshots
![image.png](https://raw.githubusercontent.com/BernardLesley/ped/main/files/ef3697a3-e0fd-4a1a-9c19-c99e64abc9f9.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: BernardLesley/ped#7

**Comment by heejet** [comment]
I think need to check if the file exist before adding
