### ISSUE TITLE
[PE-D][Tester D] Incorrect user input is not rejected

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-1/tp#193]
When user inputs command o an incorrect format (as shown in the screenshot), no warning message is produced.

![image.png](https://raw.githubusercontent.com/kaceycsn/ped/main/files/a63ed51d-73b4-43d4-a0a1-c62b56aca333.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kaceycsn/ped#11

**Comment by heejet** [comment]
Same as #189
