### ISSUE TITLE
[PE-D][Tester A] List Command additional word bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-1/tp#196]
list Command still execute even though some words has been added
![image.png](https://raw.githubusercontent.com/BernardLesley/ped/main/files/789d8916-ee3a-4e61-827f-d5d7108ed3c2.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: BernardLesley/ped#10

**Comment by heejet** [comment]
Same as #189
