### ISSUE TITLE
[PE-D][Tester E] Automatically add file

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-1/tp#200]
One function I can think of is to manually create a file.txt and add it into the folder. Right now I have to manually create and add the files which is quite troublesome. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: quanganh2810/ped#5

**Comment by heejet** [comment]
I think need to make the UG clearer that CLIAlgo is a `note management` application and not a `note taking`
